// GENERATED FILE - DO NOT EDIT
import { ModelSpec } from "../spec/appSpec";
import * as fs from 'fs/promises';
import * as path from 'path';

export async function generatePrisma(models: ModelSpec[], outDir: string) {
  const prismaDir = path.join(outDir, 'prisma');
  await fs.mkdir(prismaDir, { recursive: true });

  const schemaPath = path.join(prismaDir, 'schema.prisma');

  let schema = `// GENERATED FILE - DO NOT EDIT
// This file is automatically generated by the Lovable Offline compiler.

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}
`;

  const modelsToGenerate = [...models];

  // If no models defined, add a dummy one to prevent 'prisma generate' failure
  if (modelsToGenerate.length === 0) {
    modelsToGenerate.push({
      name: 'SystemHealth',
      fields: [{ name: 'status', type: 'string' }]
    });
  }

  for (const model of modelsToGenerate) {
    schema += `\nmodel ${model.name} {\n`;
    schema += `  id    String @id @default(cuid())\n`;

    for (const field of model.fields) {
      // Simple mapping for now based on context.md example
      // { "name": "title", "type": "string" }
      let prismaType = 'String';
      if (field.type === 'boolean') prismaType = 'Boolean';
      if (field.type === 'number') prismaType = 'Int'; // Defaulting to Int for number

      schema += `  ${field.name} ${prismaType}\n`;
    }

    schema += `}\n`;
  }

  await fs.writeFile(schemaPath, schema);
}